# Generated by Django 4.1.3 on 2022-11-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=50)),
                ('posicion', models.CharField(max_length=50)),
                ('goles', models.IntegerField()),
            ],
        ),
    ]
